### ISSUE TITLE
how to set default zoom ?

### ISSUE THREAD

**Issue by ahmedsafadii** [Tomohiro-Yamashita/VideoTimelineView#4]
is it possible to set default zoom value ?

**Comment by ahmedsafadii** [comment]
@Tomohiro-Yamashita 
can you please also tell me if  possible to disable the zoom and set static zoom value  ?

**Comment by Tomohiro-Yamashita** [comment]
## To fix the zoom
First, add the following code into TimelineView.swift
```
    func fixedWidth(_ zoomValue:CGFloat) -> CGFloat {
        let min = scroller.frameImagesView.minWidth
        let max = scroller.frameImagesView.maxWidth
        return snapWidth(min + (max - min) * zoomValue, max:max)
    }
```

Next, search the below two lines
(If you want to only set the default zoom value, the first one isn't necessary.)
```
scroller.setContentWidth(currentWidth)
```
```
scroller.setContentWidth(scroller.frameImagesView.minWidth)
```
Then replace both of them into
```
scroller.setContentWidth(fixedWidth( ZOOMVALUE ))
```
Change ZOOMVALUE with 0.0~1.0 CGFloat value





## To disable zooming
search with
```
func startPinch() {
```
And add the return command at the first like below
```
func startPinch() {
	return
	..........
}
```

**Comment by ahmedsafadii** [comment]
Thank you for that, I would like to contact you if possible,

can you provide and contact details, please?

**Comment by Tomohiro-Yamashita** [comment]
Email:
tomo@sockettv.org
